title: wtk-search
author: anon
url: https://sschmidtu.github.io/wtk-fork/
description: "wtk-search: https://sschmidtu.github.io/wtk-fork/"

permalink: /:title/

exclude:
 - README.md
 - CNAME

gems:
 - jekyll-redirect-from
