title: Multi-Radical Kanji Search (WTK)
author: anon
url: https://sschmidtu.github.io/wtk-fork/
description: "wtk-search: https://sschmidtu.github.io/wtk-fork/ - prototype!"

permalink: /:title/

exclude:
 - README.md
 - CNAME

gems:
 - jekyll-redirect-from
